[versions]
agp = "8.13.1"
fontawesome = "0.1.0"
fontawesomeVersion = "0.1.0"
githubFontawesome = "Tag-0.1.0"
googleMaterial = "1.12.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.11.0"
constraintlayout = "2.1.4"
materialVersion = "1.12.0"

[libraries]
android-hive-fontawesome = { module = "com.github.android-hive:fontawesome", version.ref = "fontawesomeVersion" }
fontawesome = { group = "info.androidhive", name = "fontawesome", version.ref = "fontawesome" }
github-fontawesome = { module = "com.github.android-hive:FontAwesome", version.ref = "githubFontawesome" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

